# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='OuterTest.InnerTest',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x13OuterTest.InnerTest\"\x97\x02\n\x0bTestMessage\x12\x1a\n\rstring_member\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nint_member\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x13repeated_int_member\x18\x03 \x03(\x05\x12\x1e\n\x16repeated_string_member\x18\x04 \x03(\t\x12\x43\n\nmap_member\x18\x05 \x03(\x0b\x32/.OuterTest.InnerTest.TestMessage.MapMemberEntry\x1a\x30\n\x0eMapMemberEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x10\n\x0e_string_memberB\r\n\x0b_int_member\"\x97\x01\n\x11TestNestedMessage\x12\x42\n\x13test_message_member\x18\x01 \x01(\x0b\x32 .OuterTest.InnerTest.TestMessageH\x00\x88\x01\x01\x12\x17\n\nint_member\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x16\n\x14_test_message_memberB\r\n\x0b_int_member\"e\n\x0bTestRequest\x12\x17\n\nrequest_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1b\n\x0erequest_string\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_request_idB\x11\n\x0f_request_string\"j\n\x0cTestResponse\x12\x18\n\x0bresponse_id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x0fresponse_string\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_response_idB\x12\n\x10_response_string2e\n\x0eTestRPCService\x12S\n\x0cGetSomething\x12 .OuterTest.InnerTest.TestRequest\x1a!.OuterTest.InnerTest.TestResponseb\x06proto3'
)




_TESTMESSAGE_MAPMEMBERENTRY = _descriptor.Descriptor(
  name='MapMemberEntry',
  full_name='OuterTest.InnerTest.TestMessage.MapMemberEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='OuterTest.InnerTest.TestMessage.MapMemberEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='OuterTest.InnerTest.TestMessage.MapMemberEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=282,
)

_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='OuterTest.InnerTest.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_member', full_name='OuterTest.InnerTest.TestMessage.string_member', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_member', full_name='OuterTest.InnerTest.TestMessage.int_member', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeated_int_member', full_name='OuterTest.InnerTest.TestMessage.repeated_int_member', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeated_string_member', full_name='OuterTest.InnerTest.TestMessage.repeated_string_member', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_member', full_name='OuterTest.InnerTest.TestMessage.map_member', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TESTMESSAGE_MAPMEMBERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_string_member', full_name='OuterTest.InnerTest.TestMessage._string_member',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_int_member', full_name='OuterTest.InnerTest.TestMessage._int_member',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=36,
  serialized_end=315,
)


_TESTNESTEDMESSAGE = _descriptor.Descriptor(
  name='TestNestedMessage',
  full_name='OuterTest.InnerTest.TestNestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_message_member', full_name='OuterTest.InnerTest.TestNestedMessage.test_message_member', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_member', full_name='OuterTest.InnerTest.TestNestedMessage.int_member', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_test_message_member', full_name='OuterTest.InnerTest.TestNestedMessage._test_message_member',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_int_member', full_name='OuterTest.InnerTest.TestNestedMessage._int_member',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=318,
  serialized_end=469,
)


_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='OuterTest.InnerTest.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='OuterTest.InnerTest.TestRequest.request_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_string', full_name='OuterTest.InnerTest.TestRequest.request_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_request_id', full_name='OuterTest.InnerTest.TestRequest._request_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_request_string', full_name='OuterTest.InnerTest.TestRequest._request_string',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=471,
  serialized_end=572,
)


_TESTRESPONSE = _descriptor.Descriptor(
  name='TestResponse',
  full_name='OuterTest.InnerTest.TestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_id', full_name='OuterTest.InnerTest.TestResponse.response_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_string', full_name='OuterTest.InnerTest.TestResponse.response_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_response_id', full_name='OuterTest.InnerTest.TestResponse._response_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_response_string', full_name='OuterTest.InnerTest.TestResponse._response_string',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=574,
  serialized_end=680,
)

_TESTMESSAGE_MAPMEMBERENTRY.containing_type = _TESTMESSAGE
_TESTMESSAGE.fields_by_name['map_member'].message_type = _TESTMESSAGE_MAPMEMBERENTRY
_TESTMESSAGE.oneofs_by_name['_string_member'].fields.append(
  _TESTMESSAGE.fields_by_name['string_member'])
_TESTMESSAGE.fields_by_name['string_member'].containing_oneof = _TESTMESSAGE.oneofs_by_name['_string_member']
_TESTMESSAGE.oneofs_by_name['_int_member'].fields.append(
  _TESTMESSAGE.fields_by_name['int_member'])
_TESTMESSAGE.fields_by_name['int_member'].containing_oneof = _TESTMESSAGE.oneofs_by_name['_int_member']
_TESTNESTEDMESSAGE.fields_by_name['test_message_member'].message_type = _TESTMESSAGE
_TESTNESTEDMESSAGE.oneofs_by_name['_test_message_member'].fields.append(
  _TESTNESTEDMESSAGE.fields_by_name['test_message_member'])
_TESTNESTEDMESSAGE.fields_by_name['test_message_member'].containing_oneof = _TESTNESTEDMESSAGE.oneofs_by_name['_test_message_member']
_TESTNESTEDMESSAGE.oneofs_by_name['_int_member'].fields.append(
  _TESTNESTEDMESSAGE.fields_by_name['int_member'])
_TESTNESTEDMESSAGE.fields_by_name['int_member'].containing_oneof = _TESTNESTEDMESSAGE.oneofs_by_name['_int_member']
_TESTREQUEST.oneofs_by_name['_request_id'].fields.append(
  _TESTREQUEST.fields_by_name['request_id'])
_TESTREQUEST.fields_by_name['request_id'].containing_oneof = _TESTREQUEST.oneofs_by_name['_request_id']
_TESTREQUEST.oneofs_by_name['_request_string'].fields.append(
  _TESTREQUEST.fields_by_name['request_string'])
_TESTREQUEST.fields_by_name['request_string'].containing_oneof = _TESTREQUEST.oneofs_by_name['_request_string']
_TESTRESPONSE.oneofs_by_name['_response_id'].fields.append(
  _TESTRESPONSE.fields_by_name['response_id'])
_TESTRESPONSE.fields_by_name['response_id'].containing_oneof = _TESTRESPONSE.oneofs_by_name['_response_id']
_TESTRESPONSE.oneofs_by_name['_response_string'].fields.append(
  _TESTRESPONSE.fields_by_name['response_string'])
_TESTRESPONSE.fields_by_name['response_string'].containing_oneof = _TESTRESPONSE.oneofs_by_name['_response_string']
DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['TestNestedMessage'] = _TESTNESTEDMESSAGE
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['TestResponse'] = _TESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), {

  'MapMemberEntry' : _reflection.GeneratedProtocolMessageType('MapMemberEntry', (_message.Message,), {
    'DESCRIPTOR' : _TESTMESSAGE_MAPMEMBERENTRY,
    '__module__' : 'test_pb2'
    # @@protoc_insertion_point(class_scope:OuterTest.InnerTest.TestMessage.MapMemberEntry)
    })
  ,
  'DESCRIPTOR' : _TESTMESSAGE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:OuterTest.InnerTest.TestMessage)
  })
_sym_db.RegisterMessage(TestMessage)
_sym_db.RegisterMessage(TestMessage.MapMemberEntry)

TestNestedMessage = _reflection.GeneratedProtocolMessageType('TestNestedMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTNESTEDMESSAGE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:OuterTest.InnerTest.TestNestedMessage)
  })
_sym_db.RegisterMessage(TestNestedMessage)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:OuterTest.InnerTest.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestResponse = _reflection.GeneratedProtocolMessageType('TestResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:OuterTest.InnerTest.TestResponse)
  })
_sym_db.RegisterMessage(TestResponse)


_TESTMESSAGE_MAPMEMBERENTRY._options = None

_TESTRPCSERVICE = _descriptor.ServiceDescriptor(
  name='TestRPCService',
  full_name='OuterTest.InnerTest.TestRPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=682,
  serialized_end=783,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSomething',
    full_name='OuterTest.InnerTest.TestRPCService.GetSomething',
    index=0,
    containing_service=None,
    input_type=_TESTREQUEST,
    output_type=_TESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTRPCSERVICE)

DESCRIPTOR.services_by_name['TestRPCService'] = _TESTRPCSERVICE

# @@protoc_insertion_point(module_scope)
